### ISSUE TITLE
Not compatible with gibbon 2.0 and MailChimp V3.0 API

### ISSUE THREAD

**Issue by plaksel** [RailsApps/rails-mailinglist-activejob#3]
Gem file need to be changed to:

gem 'gibbon', '~> 1.2.0'

app is not compatible with Gibbon 2.0 which now supports the MailChimp V3.0 API

**Comment by DanielKehoe** [comment]
Discussed here: https://github.com/amro/gibbon/issues/131
and added to the To Do list :-)

**Comment by DanielKehoe** [comment]
Gibbon 2.0.0 was released July 29, 2015.

When you run `bundle install` or `bundle update` the newest Gibbon 2.0 gem will be installed and the application will error with

```
NameError: uninitialized constant Gibbon::API
```

Either change the Gemfile and specify 

```
gem 'gibbon',  '~>1.2.0'
```

or update the code that uses Gibbon.
