### ISSUE TITLE
Certificate validate failed

### ISSUE THREAD

**Issue by jordimarti** [RailsApps/rails-mailinglist-activejob#4]
I built the Rails Mailing List Activejob from rails composer and I get this error in logs:

Gibbon::MailChimpError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

Any thoughts about how to solve it?

**Comment by DanielKehoe** [comment]
Take a look at this article and see if it helps:
http://railsapps.github.io/openssl-certificate-verify-failed.html

Let me know the outcome please, so others will be helped.

**Comment by jordimarti** [comment]
I updated everything, including OpenSSL to 1.0.2d, and restarted the computer but the error remains.

**Comment by DanielKehoe** [comment]
Open an issue on the Gibbon repo and see if the creator can help.

**Comment by jordimarti** [comment]
OK, thank you!
